### ISSUE TITLE
how do we couple with casadi?

### ISSUE THREAD

**Issue by ghorn** [acados/acados#1]
We want to use casadi codegen and JIT compilation. The strategy at the moment is to write mostly low-level C code, and then write a `casadi::FunctionInternal` wrapper around it.

**Comment by jaeandersson** [comment]
Just to point out again: `casadi::FunctionInternal` does not have a stable API and there is no ambition in making it stable. `casadi::Callback` provides a stable API to `casadi::FunctionInternal`. Is there any good reason not to use `casadi::Callback`?

**Comment by jgillis** [comment]
As I understand, the only reason is that Callback _currently_ has no way to specify codegenerate instructions. I think that should be added from our part.

**Comment by jaeandersson** [comment]
Yeah, but that's trivial to add.

**Comment by ghorn** [comment]
Yes I believe it's just codegen missing.

**Comment by jgillis** [comment]
Sure; I understood Greg wanted to prototype right now (a matter of hours), rather than days. As soon as we have extended Callback, the work should be rebased on that.

**Comment by jaeandersson** [comment]
I'm sure Greg is able to add a callback redirection to e.g. `FunctionInternal::generateBody` in matter of minutes. By implementing the corresponding function in `CallbackInternal` and `Callback` (just make it `#ifndef SWIG` since CodeGenerator is only partially exposed to SWIG).

**Comment by jaeandersson** [comment]
Those two functions have one line and two lines of code respectively...

**Comment by roversch** [comment]
We chose for a loose coupling with Casadi, basically code generating models and dynamically loading them into `acados`. I'll close this issue for now, if we want tighter coupling to Casadi, e.g. as a plugin, we can reopen the discussion.
