### ISSUE TITLE
BLASFEO?

### ISSUE THREAD

**Issue by giaf** [acados/acados#10]
I would like to open this issue to start a discussion about the use of BLASFEO in ACADOS.

At the moment, BLASFEO is in early stage, but it looks promising. 

A key feature is the use of a C struct to define a matrix and therefore completely hide all details about the matrix format and the like.
The idea is to have at least two implementations: one based on custom LA routines optimized for embedded optimization (see HPMPC LA), one as a wrapper on top of BLAS.

This feature can be the key for an early adoption of BLASFEO. It is easy and relatively quick and bug-free to write the wrappers on top of BLAS, and therefore it would be possible to get started with BLASFEO very soon. As soon as the custom LA routines are ready, it would be possible to switch to them by just changing a compilation flag in BLASFEO itself.

It would also be possible to add the reference (Netlib) BLAS and LAPACK implementations to BLASFEO itself, in order to make it pretty much self-contained. Then if better implementations are available (e.g. OpenBLAS or MKL), they could be used instead.

The main drawback of the fact that the matrix struct can have different implementations is that it is not possible to operate on it directly, but proper functions have to be used also e.g. to access the single matrix elements or extract a row/column from a matrix.

**Comment by rienq** [comment]
I think this is a great idea! :+1:  Personally, I would really like to implement collocation in acados immediately using BLASFEO to see how it compares with the original ACADO implementation.. probably I will do this soon after my thesis submission ;-)
