### ISSUE TITLE
Install acados for Raspberry Pi (Raspbian)

### ISSUE THREAD

**Issue by doanminhdang** [acados/acados#105]
Some modifications:
+ Compile CasADi from source and install it to the system (see also https://github.com/acados/acados/issues/104)
+ Install packages for compiling swig in Raspbian: automake libpcre3 libpcre3-dev
+ Add a hint to point to Fortran lib path in Raspbian: /usr/lib/gcc/arm-linux-gnueabihf/*
```
find_library(FORTRAN_LIBRARY gfortran
    HINTS
        /usr/lib/gcc/x86_64-linux-gnu/*
        /usr/lib/gcc/arm-linux-gnueabihf/*
        /usr/local/lib/gcc/*
        ${CMAKE_FIND_ROOT_PATH}
    CMAKE_FIND_ROOT_PATH_BOTH)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(FortranLibs FOUND_VAR FORTRANLIBS_FOUND
                                         REQUIRED_VARS FORTRAN_LIBRARY)
```
+ Library of python3 in Raspbian is also at different location than in Ubuntu:
Ubuntu: /usr/lib/libpython3.4.so
Raspbian: usr/lib/python3.4/config-3.4m-arm-linux-gnueabihf/libpython3.4.so

I made a symlink of python3 lib for quick fix, however the differences in path should be addressed in cmake setting.

**Comment by roversch** [comment]
> Compile CasADi from source and install it to the system

See comment in #104 

> Install packages for compiling swig in Raspbian: automake libpcre3 libpcre3-dev

I already added those recently.

> Add a hint to point to Fortran lib path in Raspbian: /usr/lib/gcc/arm-linux-gnueabihf/*

Great! Thanks for looking into this.

> I made a symlink of python3 lib for quick fix, however the differences in path should be addressed in cmake setting.

You can do this as follows: 

    cmake -D PYTHON_LIBRARY=<path/to/pythonlib> -D PYTHON_INCLUDE_DIR=<to/include>
