### ISSUE TITLE
Nan in solution whenever square root is used in contraints. 

### ISSUE THREAD

**Issue by Hamza-Robotics** [acados/acados#1063]
I encountered a bug in the Acados program when using the sqrt function inside model.con_h_expr to define constraints that use square root. Whenever sqrt is utilized within this context, it results in a nan error in the OCP, which is unexpected behavior.

**Steps to Reproduce:**
- Define a mathematical expression using sqrt within the model.con_h_expr.  I used an Euclidean distance constraint using my model variables. 
- Run the program with the defined expression.
- Observe the OCP stat output, which will includes a nan error.

**Expected Behavior:**
The program should be able to handle mathematical expressions containing sqrt within model.con_h_expr without resulting in nan errors. I understand that negative numbers passed to sqrt would give nan but Euclidian distance should be something that could be put as a constraint. 

I am not the first to mention [this, ](https://discourse.acados.org/t/i-found-that-if-i-use-sqrt-or-power-0-5-in-acados-python-with-casadi-it-produces-nan/1254) as this was posted in the forum. For now in my application I am using a Manhatten distance but could be nice to fix it. 

I know in my case I can square the expression to get rid of the square root but it would be nice to fix the bug as I used a lot of development time before I pinpointed the sqrt as the issue.

**Comment by sandmaennchen** [comment]
Hi Hamza, `acados` is numerical solver tailored to OCP structured NLPs and as such relies heavily on derivative information. As the [derivative of the square root function](https://www.wolframalpha.com/input?i=derivative+of+sqrt%28x%29+as+x+tends+to+0) $\sqrt{x}$ approaches infinity as $x \rightarrow 0$,  you may encounter numerical issues when linearizing a constraint including a Euclidian distance. Please use $\sqrt{x + \epsilon}$ with $\epsilon > 0$ to avoid this problem.
