### ISSUE TITLE
race car example

### ISSUE THREAD

**Issue by AndreCasto** [acados/acados#1077]
Hi,

I have a problem running the race car example in matlab.
All the other examples works.
It stops and returns me:
“Error using main
acados returned status 4 in closed loop iteration 8. Exiting.”

If anyone can help me.

Thanks

**Comment by FreyJo** [comment]
Fixed here https://github.com/acados/acados/pull/1078
See also https://discourse.acados.org/t/race-car-example/1559/3

**Comment by AndreCasto** [comment]
Thank you.
