### ISSUE TITLE
AcadosSimSolver missing `acados_lib_uses_omp` property

### ISSUE THREAD

**Issue by hshose** [acados/acados#1106]
I believe that the `AcadosSimBatchSolver` is checking for a property `acados_lib_uses_omp`  which doesn't work:
https://github.com/acados/acados/blob/dcfdb1ea4e4c18be11de2d894b9509f2652bf567/interfaces/acados_template/acados_template/acados_sim_batch_solver.py#L37-L38

Firstly, `AcadosSimBatchSolver` has no list attribute `ocp_solvers`, I assume this should be `sim_solvers`, second, the `sim_solvers` are missing the property field, even though a private attribute is set here:
https://github.com/acados/acados/blob/dcfdb1ea4e4c18be11de2d894b9509f2652bf567/interfaces/acados_template/acados_template/acados_sim_solver.py#L272-L281

**Comment by sandmaennchen** [comment]
fixed by @hshose in https://github.com/acados/acados/pull/1107 :rocket:
