### ISSUE TITLE
libblasfeo.so: undefined symbol: kernel_dpack_buffer_ft

### ISSUE THREAD

**Issue by giulioturrisi** [acados/acados#1237]
Hi, 

I recently installed acados from zero in two different PC, and I have noticed the following error related with blasfeo when launching my controller.

OSError: /home/iit.local/gturrisi/mambaforge/envs/quadruped_pympc_steroids_env/bin/../lib/libblasfeo.so: undefined symbol: kernel_dpack_buffer_ft
Segmentation fault

The issue both appear in ubuntu 22/24, using different version of python, both with the latest acados master and older acados commit (latest release).

Giulio

**Comment by FreyJo** [comment]
Hi Giulio,
could you provide some more information:
How do you compile acados?
Do you have a minimal example to reproduce this?
What CPU are you using?
This would greatly help to look into it.
Best,
Jonathan

**Comment by giulioturrisi** [comment]
Sure! So, the instruction and example are here:
https://github.com/iit-DLSLab/Quadruped-PyMPC

The CPU are an Intel i7-13700h and and i7-10gen (on the two different machines i tested It)

**Comment by giulioturrisi** [comment]
As additional information, it was casadi. In my yaml file, i was installing its lates version (along with pinocchio https://github.com/stack-of-tasks/pinocchio), which create a libblasfeo.so that is incompatible with acados. 
Setting as requirement ==3.6.5 (the latest supported version by acados), solved this problem since no libblasfeo.so is created.
