### ISSUE TITLE
Proper unit-testing for interfaced QP solvers

### ISSUE THREAD

**Issue by dkouzoup** [acados/acados#124]
- Rewrite tests in python and perhaps get rid of catch+eigen
- Add tests for missing solvers (i.e. hpipm & condensing+hpipm)
- Check also multipliers (currently only  checking primal solution)

**Comment by roversch** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Write Python automated tests for all modules](https://trello.com/c/BPcC336l/9-write-python-automated-tests-for-all-modules)
