### ISSUE TITLE
Warnings in auto generated code

### ISSUE THREAD

**Issue by rienq** [acados/acados#13]
Currently all files in acados, including auto generated files from CasADi for the test problems, are compiled with all warnings raising errors. This creates a lot of errors like this:

error: unused parameter ‘w’
error: unused parameter ‘iw’
error: unused parameter ‘mem’
...

There should be a convenient way to add and remove these compiler flags for specific source files.

**Comment by jaeandersson** [comment]
Related: https://github.com/casadi/casadi/issues/1741

**Comment by roversch** [comment]
There is a workaround now, using the `sed` utility to add dummy code. @jaeandersson Would be nice to have a solution from Casadi ;)
