### ISSUE TITLE
Unifying cast_worspace utilities 

### ISSUE THREAD

**Issue by zanellia** [acados/acados#135]
cast_workspace takes (work, mem) as arguments in most modules apart from integrators, which take (work, in, mem)

**Comment by dkouzoup** [comment]
good point @zanellia. Another remark, we are currently working on major changes regarding the creation of the modules in the qp_in branch of blessed. cast is there called assign for consistency with the new changes btw. perhaps you should directly code your new features there to avoid double work?

**Comment by FreyJo** [comment]
outdated/solved.
The `*cast_workspace` functions now all use the arguments `void *config_, void *dims_, void *opts_, void *work_`
