### ISSUE TITLE
How to update the model dynamically?

### ISSUE THREAD

**Issue by liu2050** [acados/acados#1373]
In my project, some dynamic parameters of the model will change with the state variables. Do I have to redefine the model and redefine the solver for each calculation?

**Comment by liu2050** [comment]
Or could it be that the dynamically changing parameters are also considered as state variables?

**Comment by sandmaennchen** [comment]
Not sure if I understand correctly, but can't you just include the dependence of $p$ on $x$ in your dynamics, i.e. use $f(x, u) = \tilde{f}(x, u, p(x))$?

**Comment by liu2050** [comment]
I‘m sorry I may not fully understand your explanation. In my project, p(x) is used to calculate f_expl_expr, and is a piecewise function with respect to x. Therefore, I need to compare x with numerical values to switch different values of p(x). However, when building the model according to the MATLAB code examples, x is defined as a sym, which cannot be compared with numerical values. I have tried to use p(x) as a new state variable, i.e., x_new = [x; p(x)], which can indirectly achieve the target, but it doesn't feel like the best solution. So, I'm wondering if there is a better way to solve this?

Additionally, when implementing the above method, I encountered a new problem. The calculation of the f_expl_expr might result in NaN values. I want to use isnan( ) to check and assign zero values, but isnan( ) can only check numerical values and cannot be applied to sym. How can I resolve this issue?

**Comment by sandmaennchen** [comment]
Is $p(x)$ non-differentiable wrt. $x$? In this case, you do not want to include it in the dynamics directly. If it does not change a lot with $x$, you might try to approximate the dynamics by using $f(x, u, p)$, i.e. omitting the dependence of the parameters on $x$ and set the parameters $p$ for each OCP/update $p$ manually after each SQP iteration.

**Comment by liu2050** [comment]
I understand now, thank you for your patience in explaining.
