### ISSUE TITLE
PR #147 broke matlab interface of condensing+qpoases (only for clang)

### ISSUE THREAD

**Issue by dkouzoup** [acados/acados#153]
The matlab example on travis is hanging. The issue did not appear before the merge since no matlab examples are executed on PR.

**Comment by dkouzoup** [comment]
@nielsvd

**Comment by bnovoselnik** [comment]
Also, Matlab tests that do pass take unusually long time, around 30 sec, while in Python it's no more than 1 sec. But, that's also true for earlier commits as well. Is this normal?

**Comment by roversch** [comment]
@bnovoselnik: Yes, that's normal. MATLAB is slow :p

As for the hanging: strange, only for one compiler. Will investigate soon

**Comment by nielsvd** [comment]
I don't have a mac on which I can test this. I can have a look on Thursday, when I'm in Freiburg, what I've changed to cause this.

**Comment by nielsvd** [comment]
No problems with clang+Matlab on my Linux installation. 
```
clang --version
clang version 5.0.0 (tags/RELEASE_500/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
```
To make sure we're talking about the same code. I run (modified from ``examples/matlab/ocp_qp_example.m``):
```matlab
import acados.*

qp = ocp_qp(struct('N',5, 'nx',2, 'nu', 1));

% specify OCP
qp.A = [0 0; 1 0];
qp.B = [0; 1];
qp.Q = eye(2);
qp.R = 1;

% specify initial condition
x0 = [1; 1];
qp.lb{1} = x0;
qp.ub{1} = x0;

% solve QP
solver = ocp_qp_solver('condensing_qpoases', qp);
output = solver.evaluate();
assert(abs(-0.5 - output.controls{1}) < 1e-8)
disp(output.states)
```

**Comment by bnovoselnik** [comment]
@nielsvd: I think the other example (ocp_nlp) is causing trouble.

**Comment by roversch** [comment]
Weird, this latest build output tells me MATLAB just hangs at startup..

https://travis-ci.org/acados/acados/jobs/294770601

**Comment by dkouzoup** [comment]
@nielsvd we could reproduce this locally on a linux machine. Try the ocp_nlp example. If it still works, try the same clang version as travis does

**Comment by FreyJo** [comment]
https://github.com/acados/acados/pull/419
