### ISSUE TITLE
Hierarchical memory model

### ISSUE THREAD

**Issue by roversch** [acados/acados#157]
We could make it clearer what the hierarchical relations between the different modules are. For example for the memory of QP, which is nested in the memory of the SQP:
```C
struct sqp_mem {
    void *qp_mem;
    ...
}
```

```C
struct qp_solver {
    void (*init)(..., void **mem, ...);
    void **qp_mem;
    ...
}
```

As you can see, the `qp_solver` struct only has a reference to the address where the memory lies. This makes it clear that SQP 'owns' the memory inside the QP solver.

Initialisation of the `qp_solver` inside the SQP initialisation could then look something like
```C
qp_solver->init(..., &sqp_mem->qp_mem, ...);
qp_solver->qp_mem = &sqp_mem->qp_mem;
```

The place where to put the `qp_solver` struct is either in the SQP 'options' or 'input':
```C
struct sqp_args {
    void *qp_solver;
    ...
}
```

The idea would be to not use the `qp_solver` as a standalone module if you only want to solve QPs. This would fit more aptly in the C++ interface (see #155). In C, you directly call the appropriate routines (e.g. `ocp_qp_condensing_qpoases`).

**Comment by FreyJo** [comment]
I think this is done now, more or less.
