### ISSUE TITLE
Automatic multi-stage structure detection

### ISSUE THREAD

**Issue by rienq** [acados/acados#16]
@dkouzoup  found out about the following interesting github repository, which we should keep in mind:
https://github.com/embotech/Y2F

They worked on a tool to automatically detect the multi-stage structure from a general (convex) optimization problem, which apparently is not only a very easy-to-use thing but also overall provides considerable speedups in the resulting FORCES solver! (the latter was also confirmed by Dimitris who used it for his tree-structured QP problem)

Maybe this could be an interesting approach to detect the multi-stage structure in the convex/non-convex optimization problems that one might formulate in CasADi, when passing them to acados (through the plugins we plan to develop, see #1)..

**Comment by jaeandersson** [comment]
Yeah, this is easy to implement. CasADi already does this for the BlockSqp code: https://github.com/casadi/casadi/blob/develop/casadi/interfaces/blocksqp/blocksqp.cpp#L415. The implementation gets even easier if we allow reordering of the variables, just call `casadi::Sparsity:scc`.

Not sure if @jgillis already added it to hpmpc too (https://github.com/casadi/casadi/issues/1865), but it's something we've talked about.

**Comment by jgillis** [comment]
Did detection, not reordering

Op 27-okt.-2016 19:13 schreef "Joel Andersson" <notifications@github.com>:

**Comment by roversch** [comment]
This is a long-term item, since we will not (for now) support acados as a plugin to CasADi.
