### ISSUE TITLE
Compiling with gcc version <6?

### ISSUE THREAD

**Issue by zanellia** [acados/acados#17]
Installation seems to be broken with gcc-4 mainly due to warnings in compiling qpOASES being treated as errors. Installs fine with gcc-6.

**Comment by giaf** [comment]
ATM as a workaround you need to remove the flag -Werror from
`set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -std=c99 -Wall -Wextra -Werror -Wno-unused-function")`
in CMakeLists.txt

But it would be nice to have a better solution.

**Comment by roversch** [comment]
gcc 4.9 and gcc 5 are now supported
