### ISSUE TITLE
Various bugs due to making assumptions on HPIPM core data layout

### ISSUE THREAD

**Issue by giaf** [acados/acados#196]
Hey  guys,

I've spent the weekend fixing bugs around acados, which are triggered by the use of BLASFEO HP version.

All bugs boil down to making assumption about the way HPIPM internally stores its variables, e.g. the (wrong) assumptions that the slacks or the residuals are stored contiguously one stage after the other.

Such assumptions can not be made, and the variables in the QP structures should be accessed using the QP structure interface (based on BLASFEO structures) and not the underlying memory arrays.

**Comment by roversch** [comment]
Can you link some examples of the bugs here? Just for our education.

**Comment by roversch** [comment]
what about calling

blasfeo_pack_tran_dmat

directly on BAbt? Is this subject to change? If so, maybe we could provide
setters/getters for each field separately, instead of converting a full
ocp_qp each time..

Side question: is the ordering in lb = [lbx, lbu] or lb = [lbu, lbx] ?

**Comment by giaf** [comment]
I didn't get the first question about BAbt...

My point here is: using the HPIPM interface is safe, making assumptions about where matrices and vectors are mapped internally in memory as arrays in HPIPM is not, as it can change with the BLASFEO LA version and/or over time.
E.g., in the piece of code above, for BLASFEO RF it works (since there is no padding in vectors), for BLASFEO HP it does not (since there is padding, and then res_g[0].pa+(nx[0]+nu[0]+2*ns[0]) != res_g[1].pa if nx[0]+nu[0]+2*ns[0] is not a multiple of 4).

About the second question, the order is [lbu, lbx]

**Comment by roversch** [comment]
I guess we have to extend the HPIPM interface then, to allow setting single
matrices/vectors.

Now, there is only row major OCP -> ocp_qp and column major OCP -> ocp_qp.

**Comment by giaf** [comment]
Yep the right way to do it is to extend HPIPM interface to allow that. When needed, we can do it.

**Comment by roversch** [comment]
I can work on that, I need it for the C++ interface anyway.

**Comment by dkouzoup** [comment]
Hey @giaf, thanks for the heads-up. I hope I didn't do that mistake so far ;)
