### ISSUE TITLE
HPMPC seg fault for BLASFEO HP

### ISSUE THREAD

**Issue by giaf** [acados/acados#197]
HPMPC gives seg fault for BLASFEO HP, due to not properly aligning memory. The interface needs to be updated to take memory alignment into account.

@zanellia can you take the lead in fixing that? I can give you support :)

**Comment by zanellia** [comment]
@giaf sure let's do asap!

**Comment by giaf** [comment]
What is the status of this?

**Comment by dkouzoup** [comment]
I did a major cleanup of the interface after the group retreat. I am guessing it's fixed.

**Comment by roversch** [comment]
@dkouzoup can we close this ?

**Comment by dkouzoup** [comment]
yeap
