### ISSUE TITLE
assert being overwritten by qpoases/qpdunes

### ISSUE THREAD

**Issue by dkouzoup** [acados/acados#217]
This is particularly "dangerous" since in many places, asserts are not actually checked because external software has overwritten it with an empty function..

**Comment by doanminhdang** [comment]
Isn't this has similar potential impact like removing the flag -Werror in compilation?
Will there be a lot of bugs if the overwritten empty functions are removed?

**Comment by dkouzoup** [comment]
> Isn't this has similar potential impact like removing the flag -Werror in compilation?
> Will there be a lot of bugs if the overwritten empty functions are removed?

not sure I understand what you mean

**Comment by dkouzoup** [comment]
closing for now, I was not compiling with Debug on.. But there is still a chance our assert is overwritten by qpoases in some places (qpoases interface?).
