### ISSUE TITLE
Restructure unit tests

### ISSUE THREAD

**Issue by dkouzoup** [acados/acados#22]
Currently, running cmake with the unit tests flag calls both octave (to generate condensing data) and a bunch of ipopt simulations (which requires quite some time). To my opinion, Cmake should only create the necessary makefiles. Then running the makefile should generate the data and compile the tests and finally, running the compiled code should run all tests.

**Comment by rienq** [comment]
we also generate with CasADi the symbolic expressions and derivatives though, so the only solution I would see at the moment (without making any of the test files part of the repo) is that we include an extra step in between so you would first call Cmake, then run a test_generation script and then run the makefile based on the unit tests and the generated files but I am not sure whether that would actually be better then..

**Comment by dkouzoup** [comment]
hmm, that's true. But can't we just call the "generation script" from the Makefile?

**Comment by roversch** [comment]
I was fixing this on Friday, let me commit that tomorrow

**Comment by roversch** [comment]
I rewrote the CMakeLists.txt such that:
- during `cmake`, only configuration of the build files is done
- during `make`, generation of Casadi functions, generation of test data and building of all targets is done.
