### ISSUE TITLE
Matlab Interface : cannot read out dimensions

### ISSUE THREAD

**Issue by dp134** [acados/acados#225]
Hey Robin @roversch ,

Please do check the Matlab interface of ACADOS, I am not able to read out the dimensions from the structure.

Thanking you.

Deep

**Comment by roversch** [comment]
@dp134 I pushed a fix in #275 , could you check if that works ?

**Comment by dkouzoup** [comment]
I tested it, good job!

**Comment by dkouzoup** [comment]
reopening this because idxb cannot be accessed neither from dimensions nor via 'extract'

**Comment by dkouzoup** [comment]
ping @roversch

**Comment by FreyJo** [comment]
https://github.com/acados/acados/pull/419
