### ISSUE TITLE
[new core] cannot use latest casadi (3.4) to code generate

### ISSUE THREAD

**Issue by dkouzoup** [acados/acados#249]
There have been changes in the code generation framework of casadi and using the latest version gives in some cases wrong results and in some others segfaults

**Comment by dkouzoup** [comment]
@jgillis, @jaeandersson any hints on what has been changed? We couldn't find with @giaf something in the release notes.

**Comment by giaf** [comment]
fixed in https://github.com/acados/acados/pull/258
