### ISSUE TITLE
different niter in wind_turbine_nmpc_example, depending on BLASFEO LA and OS

### ISSUE THREAD

**Issue by FreyJo** [acados/acados#269]
Hey guys,

for me the wind_turbine_nmpc_example fails during the ctest. I looked more into it and also ran it manually:

I went back some commits, always running "submodule update" before compiling with cmake, and found out the following:

In the commit c1cdf67f5913fcacd3dde3dde7d0e505173fc8a8, April 12th,  the example works fine for me running all 40 problems and putting out

`[...] 
success!`

In the commit d8a6a2cc9f504fe14d31504dd3e9ba2eb5058c6d, April 12th, the example stops working for me.
It outputs:
```
problem #0, status 1, iters 10
xsim = 
  1.29820   0.00000  50.19698   0.00000   6.00279   4.33119   6.00279   4.33119 

electrical power = 5.148647

residuals
res_g =
3.925749e-12	6.518341e-12	5.456968e-11	6.184564e-11	-1.172396e-13	1.127773e-10	5.883294e-12	-9.441337e-13	1.287361e-10	1.391243e-11	[...]
```

Interestingly, in more recent versions (c9716900d378c6a41bdd861ef1e4dc632765478c - from April 19th), the example fails too, but with another output:

```
problem #0, status 0, iters 9
xsim = 
  1.29820  -0.00000  50.19698   0.00000   6.00279   4.33119   6.00279   4.33119 

electrical power = 5.148647

problem #1, status 1, iters 10
xsim = 
  1.28755   0.02942  50.45517   0.00342   6.34369   4.51163   7.60279   4.53119 

electrical power = 5.319151

residuals
res_g =
4.096812e-11	3.568517e-12  [...]
```
It seems like here the first problem runs fine but in the second one the solver fails and returns status 1. So it seems that there has been a commit between 12th and 19th of April which also changed the behaviour of the ocp_nlp_solve..

@giaf  @dkouzoup : Do you have ideas where the problem is originated?

**Comment by FreyJo** [comment]
UPDATE:
I found out the example does not crash when changing

`		plan->sim_solver_plan[i].sim_solver = NEW_LIFTED_IRK;`

to

`		plan->sim_solver_plan[i].sim_solver = IRK;`

@zanellia Do you have an idea, why using this integrator causes problems?

**Comment by zanellia** [comment]
@FreyJo, it seems to work fine with MAX_SQP_ITERS >= 14 when using
plan->sim_solver_plan[i].sim_solver = NEW_LIFTED_IRK;

**Comment by giaf** [comment]
The combination of lifted_irk and soft-constraints makes the problem a bit unstable numerically. Very small differences in the numerics (like e.g. the different BLASFEO and HPIPM versions used by default in make and cmake) affect the number of SQP iterations needed to fully converge.

The easy solve it to increase the max number of SQP iterations e.g. to 15.

**Comment by dkouzoup** [comment]
output on mac (10 iterations are enough):


problem #0, status 0, iters 9
xsim =
  1.29820  -0.00000  50.19698   0.00000   6.00279   4.33119   6.00279   4.33119

electrical power = 5.148647

problem #1, status 0, iters 9
xsim =
  1.28755   0.02942  50.45517   0.00342   6.34369   4.51163   7.60279   4.53119

electrical power = 5.319151

problem #2, status 0, iters 9
xsim =
  1.30247   0.02449  50.71378   0.00932   7.18001   4.56581   9.20279   4.57004

electrical power = 5.445398

problem #3, status 0, iters 9
xsim =
  1.33201   0.00016  50.97716   0.01192   8.31681   4.46407  10.80279   4.45268

electrical power = 5.444783

problem #4, status 0, iters 6
xsim =
  1.35615  -0.01739  51.24619   0.01002   9.63587   4.37825  12.40279   4.36991

electrical power = 5.436894

problem #5, status 0, iters 4
xsim =
  1.36136  -0.02738  51.51833   0.00516  10.84025   4.18965  12.94574   4.16991

electrical power = 5.222682

problem #6, status 0, iters 4
xsim =
  1.34604  -0.01580  51.78933   0.00057  11.49850   4.05667  12.14694   4.04392

electrical power = 5.000024

problem #7, status 0, iters 4
xsim =
  1.32270   0.00174  52.05621  -0.00084  11.60018   4.03688  11.42667   4.03581

electrical power = 4.889355

problem #8, status 0, iters 5
xsim =
  1.30629   0.01648  52.31889   0.00122  11.39590   4.04730  10.78830   4.04852

electrical power = 4.841163

problem #9, status 0, iters 4
xsim =
  1.30388   0.01277  52.57970   0.00436  11.04160   4.07445  10.24751   4.07729

electrical power = 4.864636

problem #10, status 0, iters 5
xsim =
  1.30863   0.00025  52.84093   0.00566  10.63391   4.11053   9.80049   4.11421

electrical power = 4.925611

problem #11, status 0, iters 4
xsim =
  1.31046  -0.00748  53.10294   0.00479  10.22891   4.14852   9.43874   4.15233

electrical power = 4.978076

problem #12, status 0, iters 5
xsim =
  1.30506  -0.00716  53.36461   0.00317   9.85809   4.18403   9.15755   4.18756

electrical power = 5.000004

problem #13, status 0, iters 4
xsim =
  1.29492  -0.00096  53.62465   0.00231   9.53847   4.21680   8.95115   4.22006

electrical power = 5.000008

problem #14, status 0, iters 4
xsim =
  1.28481   0.00215  53.88259   0.00244   9.27228   4.25000   8.78642   4.25333

electrical power = 5.000009

problem #15, status 0, iters 5
xsim =
  1.27787   0.00598  54.13878   0.00333   9.04388   4.27307   8.61167   4.27529

electrical power = 5.000007

problem #16, status 0, iters 4
xsim =
  1.27626   0.00549  54.39411   0.00457   8.82783   4.27159   8.39583   4.27124

electrical power = 4.991996

problem #17, status 0, iters 4
xsim =
  1.27921   0.00382  54.64959   0.00556   8.60106   4.23530   8.12927   4.23139

electrical power = 4.961013

problem #18, status 0, iters 4
xsim =
  1.28388  -0.00186  54.90591   0.00572   8.34774   4.17213   7.81160   4.16561

electrical power = 4.904855

problem #19, status 0, iters 4
xsim =
  1.28741  -0.00076  55.16305   0.00543   8.06129   4.09980   7.45727   4.09250

electrical power = 4.833071

problem #20, status 0, iters 4
xsim =
  1.29015  -0.00176  55.42083   0.00513   7.74943   4.03934   7.10904   4.03340

electrical power = 4.771921

problem #21, status 0, iters 5
xsim =
  1.29135  -0.00187  55.67901   0.00472   7.43239   4.00557   6.80363   4.00240

electrical power = 4.736437

problem #22, status 0, iters 4
xsim =
  1.29070  -0.00224  55.93725   0.00425   7.13585   4.00630   6.57299   4.00665

electrical power = 4.734920

problem #23, status 0, iters 6
xsim =
  1.28853  -0.00019  56.19518   0.00399   6.88912   4.04672   6.45444   4.05108

electrical power = 4.774656

problem #24, status 0, iters 4
xsim =
  1.28557  -0.00110  56.45261   0.00383   6.72375   4.12164   6.48101   4.12939

electrical power = 4.851874

problem #25, status 0, iters 4
xsim =
  1.28104  -0.00145  56.70930   0.00355   6.66489   4.21189   6.65306   4.22102

electrical power = 4.940629

problem #26, status 0, iters 4
xsim =
  1.27452  -0.00213  56.96490   0.00316   6.71803   4.28297   6.92431   4.28991

electrical power = 4.998438

problem #27, status 0, iters 6
xsim =
  1.26699   0.00129  57.21904   0.00309   6.86356   4.30977   7.22640   4.31209

electrical power = 5.000014

problem #28, status 0, iters 5
xsim =
  1.26154   0.00388  57.47183   0.00368   7.06964   4.32837   7.52356   4.33020

electrical power = 5.000013

problem #29, status 0, iters 4
xsim =
  1.25980   0.00410  57.72390   0.00456   7.30666   4.33436   7.79774   4.33486

electrical power = 5.000015

problem #30, status 0, iters 4
xsim =
  1.26083   0.00099  57.97594   0.00511   7.55118   4.33083   8.03848   4.33041

electrical power = 5.000017

problem #31, status 0, iters 4
xsim =
  1.26190  -0.00162  58.22824   0.00503   7.78367   4.32718   8.22976   4.32682

electrical power = 5.000018

problem #32, status 0, iters 4
xsim =
  1.26147  -0.00162  58.48060   0.00469   7.98562   4.32863   8.35381   4.32882

electrical power = 5.000014

problem #33, status 0, iters 5
xsim =
  1.26115   0.00287  58.73282   0.00487   8.14429   4.32971   8.41855   4.32982

electrical power = 5.000009

problem #34, status 0, iters 5
xsim =
  1.26319   0.00169  58.98523   0.00536   8.25970   4.32275   8.45375   4.32198

electrical power = 5.000010

problem #35, status 0, iters 4
xsim =
  1.26497  -0.00365  59.23809   0.00512   8.33561   4.30665   8.45167   4.30497

electrical power = 4.988419

problem #36, status 0, iters 4
xsim =
  1.26375  -0.00287  59.49100   0.00441   8.36600   4.24871   8.37997   4.24257

electrical power = 4.916554

problem #37, status 0, iters 4
xsim =
  1.26154   0.00081  59.74352   0.00421   8.33646   4.14661   8.21551   4.13605

electrical power = 4.790007

problem #38, status 0, iters 4
xsim =
  1.26263   0.00638  59.99583   0.00503   8.23427   4.01417   7.95928   4.00070

electrical power = 4.641043

problem #39, status 0, iters 4
xsim =
  1.26957   0.00413  60.24897   0.00615   8.05781   3.87165   7.63887   3.85734

electrical power = 4.500875


total time (including printing) = 647.364187 ms (time per SQP = 16.184105)


success!

**Comment by zanellia** [comment]
So, recap. Convergence can be achieved in < 10 iterations when using the GENERIC target on Mac, but not on Linux. Convergence can be achieved in < 10 iterations when using the HASWELL target on Linux.
