### ISSUE TITLE
add check for "model not initialized"

### ISSUE THREAD

**Issue by giaf** [acados/acados#280]
When some of the external functions are not provided, acados gives seg-fault. This is not a very informative output, and therefore I would suggest to add (maybe to the c interface) checks to ensure external functions are provided as they should be, and return a more informative output otherwise.

**Comment by FreyJo** [comment]
Given that this is now basically automated by the interfaces, I don't think it is still necessary.
Do you agree?
Otherwise, that would mean adding a check that the function pointer is not NULL before calling external functions in the core.
