### ISSUE TITLE
ocp_nlp.py occasionally segfaulting on travis

### ISSUE THREAD

**Issue by dkouzoup** [acados/acados#306]
Since we merged the two PRs: #302 and #296 the ocp_nlp example in python fails sometimes on travis (typically 1 out of 4 builds). The issue must be related to the fact that nz is not considered yet in the higher level interfaces.

**Comment by dkouzoup** [comment]
I suggest @FreyJo assists @roversch  to fix this issue.

**Comment by FreyJo** [comment]
outdated, since we dont use the SWIG generated python interface anymore
