### ISSUE TITLE
Partial tightening in acados

### ISSUE THREAD

**Issue by zanellia** [acados/acados#32]
Development of an interface to hpmpc that enables the use of partial tightening. A line-search has to be implemented in acados to avoid dual-infeasible problems.

**Comment by roversch** [comment]
Need to migrate to HPIPM.

**Comment by dkouzoup** [comment]
There has been one, but currently it's broken, write @zanellia? What are you planning to do with partial tightening in acados? Migrate to HPIPM, restore it in HPMPC, both?

**Comment by zanellia** [comment]
Both actually. Although, unfortunately, I have to admit it is not high
priority at the moment.
