### ISSUE TITLE
GPL lincense in BLASFEO and HPIPMP: linking issues

### ISSUE THREAD

**Issue by giaf** [acados/acados#320]
As of yesterday afternoon, both BLASFEO and HPIPM are GPLv3 + CE, instead of LGPLv2.1.

Therefore, their libraries can not be included into the libacados.a library (since acados is LGPL), but they should be stand alone. Linking is permitted at the instant of creating the executable.

Besides these legal issues, as BLASFEO and HPIPM developer I am against the option of having a single libacados.a incorporating libblasfeo.a and libhpipm.a (and libhpmpc.a too), as this removes the last bit of visibility (after git submodules take away most of it).

**Comment by giaf** [comment]
So, if BLASFEO and HPIPM are not already stand alone libraries in both make and cmake build systems, this should be fixed before upgrading their version used in acados.

**Comment by FreyJo** [comment]
I guess this issue is solved/outdated given the latest license changes to BSD-2 of acados, HPIPM and soon also BLASFEO.
https://github.com/acados/acados/pull/401
