### ISSUE TITLE
OOQP related issues

### ISSUE THREAD

**Issue by bnovoselnik** [acados/acados#321]
Travis experiences a segfault in unit tests (both ocp qp and ocp nlp) whenever an OOQP solver is called. I have not been able to reproduce this locally (with the same compiler, in both release and debug mode, etc.). 

On the other hand, Travis doesn't have problems with OOQP in stand-alone examples (e.g. the mass spring example).

**Comment by sandmaennchen** [comment]
bye travis :wave: https://github.com/acados/acados/pull/668
