### ISSUE TITLE
Pendulum example ocp_nlp error

### ISSUE THREAD

**Issue by kalatta** [acados/acados#335]
Hello,

I just picked up acados for matlab on windows and I am trying to learn how to use it.
I have been exploring the examples, but I keep runing into some errors.
For example with the 'ocp_nlp_example': the code call for the 'ocp_nlp' simulink, but I get an error saying that the s_function does not take the provided number of arguments (N, nx, nu). I tried to look into the simulink model and maybe generate a new s_function but I don't know how to generate it. I have only been able to generate other c code for the pendulum example using 'generate_C_model'.

Thanks in advance.
![capture](https://user-images.githubusercontent.com/43576026/46017207-3ab14d80-c0d7-11e8-8bcc-fb7e8d11809f.PNG)

**Comment by dkouzoup** [comment]
Hi,

apart from the generation of the simulink block (perhaps @roversch can help you with this error), does the matlab interface work properly? i.e., can you solve the NLP in matlab?

**Comment by kalatta** [comment]
Hello,

I am not sure how to define an nlp problem in order to try to solve it. Trying another example such as 'sim_example', that does not use simulink, does not work either because 'sim_solver' cannot be found.

**Comment by FreyJo** [comment]
Hey,

was talking with @roversch last week.
He said integrator interface is outdated/ not supported. We want to provide a new one soon.
However, the `sim_example` is definitely broken and should be removed!

**Comment by FreyJo** [comment]
Update,
we have a new Matlab/Octave interface, that is not using SWIG, but implemented in MEX.
If you are still interested please try our examples in:
https://github.com/acados/acados/tree/master/examples/matlab_mex
