### ISSUE TITLE
Plotting

### ISSUE THREAD

**Issue by zanellia** [acados/acados#37]
Adding plotting with gnuplot directly from C code using pipes.

**Comment by roversch** [comment]
Are you sure you want to go on with this? Otherwise we could close this issue.

**Comment by zanellia** [comment]
hahah I missed @jgillis's reaction. Well, now that we have a Python interface plotting from will be much easier, but back then it was the most natural thing I could come up with. Some of the examples I wrote/worked on do have plotting with gnuplot. I think it could still be useful to have a low level plotter that can be called without accessing the Python interface. Probably not highest priority.
