### ISSUE TITLE
URL to the documentation

### ISSUE THREAD

**Issue by jkoendev** [acados/acados#399]
Hi where are the docs again? Would make sense to link them on the github somewhere. 

It used to be [https://acados.syscop.de/](https://acados.syscop.de/) i think but now this redirects to BLASFEO..

Jonas

**Comment by giaf** [comment]
@tmmsartor do you know anything about?
```It used to be https://acados.syscop.de/ i think but now this redirects to BLASFEO..```

**Comment by tmmsartor** [comment]
The link has been fixed.
