### ISSUE TITLE
Mex interface, time optimal control

### ISSUE THREAD

**Issue by jkoendev** [acados/acados#414]
Is it enough to just not set `ocp_model.set('T', T)`? 

Feature request:
I think getting the solution for the final time using `ocp.get('T')` is not yet implemented.

**Comment by jkoendev** [comment]
i tried getting:
```
error: ocp_create: T not set!
```

**Comment by zanellia** [comment]
T is not an optimization variable in acados at the moment. Time-optimal formulations can be implemented using time transformations instead.

**Comment by jkoendev** [comment]
ok thanks! The transformation does not seem trivial to me for a general problem. Have you/somebody got some code to do the coordinate transformation for some problem? Do you have a model for a time-transformed cartpole-swingup somewhere (time optimal swingup)?
