### ISSUE TITLE
compile_interface=auto

### ISSUE THREAD

**Issue by giaf** [acados/acados#485]
@FreyJo by using a bit the mex interface now, I think that the option `compile_interface` should take the values `true` (always do), `false` (never do), and `auto` (that is what you implemented now), otherwise the name is quite misleading in my opinion.

**Comment by FreyJo** [comment]
fixed in https://github.com/acados/acados/pull/481/commits/71ad0c84079a780d9c7a14a66e1b962765a5cd83
included in #481

**Comment by FreyJo** [comment]
closing, the fix is merged into master
