### ISSUE TITLE
problem with access to acados documentation website

### ISSUE THREAD

**Issue by BilloAldi** [acados/acados#511]
Hi guys,
I can not connect anymore to the website https://docs.acados.org/

it gives me: 

403 Forbidden
nginx/1.16.1

https://docs.acados.org/interfaces/index.html
gives me:
 
404 Not Found
nginx/1.16.1

I can not access from smartphone or PC  (I used to some days ago).

**Comment by tmmsartor** [comment]
Now it should be up and running again. 
Thanks for notifying us!
