### ISSUE TITLE
Breaking blessed/master

### ISSUE THREAD

**Issue by zanellia** [acados/acados#52]
I mixed up my remotes and ended up braking blessed/master (I reverted everything and pushed to a separate branch. As soon as Travis says it is OK I will push again to master)...Shouldn't we force people to go through a merge such that changes run through Travis before ending up in the master branch? I guess this simply boils down to denying push rights to everybody. I had to revert 15 commits with 2 merges in between... :)

**Comment by roversch** [comment]
It seems from [this SO post](http://stackoverflow.com/questions/19734148/restricting-rights-on-github#19734387) that that's not possible.

If you know a way, I would be glad to change the settings accordingly.

**Comment by mvukov** [comment]
https://help.github.com/articles/about-protected-branches/

**Comment by roversch** [comment]
Wait a moment, the `master` branch is already protected..

**Comment by roversch** [comment]
Closing this, as there is no easy solution.

**Comment by roversch** [comment]
FYI, Gitlab has this possibility.
