### ISSUE TITLE
Cost modules: add support for algebraic variables z

### ISSUE THREAD

**Issue by FreyJo** [acados/acados#554]
Currently only supported in for LINEAR_LS cost.
TODO: add support in cost modules
- [x] NON_LINEAR_LS
- [x] EXTERNAL

See,
https://discourse.acados.org/t/mhe-using-algebraic-variables

**Comment by SihaoSun** [comment]
Hi FreyJo, thanks for posting this issue. I'm trying to build a nonlinear cost function with algebraic variables. Could you please tell me if this issue has been resolved?

**Comment by sandmaennchen** [comment]
Done! Please check #875 and #894 :tractor:
