### ISSUE TITLE
Proper modular build, link, install

### ISSUE THREAD

**Issue by zanellia** [acados/acados#56]
Right now ExternalProjects (or some of them at least, like hpmpc and blasfeo) have _INSTALL_COMMAND " "_ in order to avoid cmake runnig install whenever a build is called. However this causes ExternalProjects not being installed properly when _make install_ is called. I bring this up because proper installation might be rather important for integration in more complex build systems and for portability to embedded platforms. I am looking into something like this: [http://www.stackoverflow.com/questions/37838786/how-to-not-make-install-step-when-building-external-project-with-cmake](url) at the moment. If you happen to have better ideas, please let me know, I actually need right now.

EDIT: github breaks the link, dunno why. Copy paste will do.

**Comment by roversch** [comment]
I like that solution! It's pretty clean.

**Comment by roversch** [comment]
Although we want to be modular, it's not really possible to leave out some subprojects, e.g. qpDUNES.

**Comment by roversch** [comment]
We also decided to install all subprojects independently, along with a big library including all dependents.

**Comment by roversch** [comment]
@zanellia can I close this? The install is done in a modular fashion since some time now.

**Comment by zanellia** [comment]
Sure ;)

On Tue, Feb 13, 2018 at 9:56 AM, Robin Verschueren <notifications@github.com
