### ISSUE TITLE
Behavior of make clean

### ISSUE THREAD

**Issue by zanellia** [acados/acados#57]
make clean seems not to be cleaning all the binaries

**Comment by roversch** [comment]
Can you be more specific? Which ones do you mean? 

The right way to do this in CMake seems to be [like this](https://cmake.org/Wiki/CMake_FAQ#Running_.22make_clean.22_does_not_remove_custom_command_outputs._Why.3F).

**Comment by zanellia** [comment]
In particular, it does not clean hpmpc and blasfeo.

**Comment by roversch** [comment]
@zanellia will integrate his version of CMake for hpmpc

**Comment by roversch** [comment]
Since #122 hpmpc has cmake. Note that ooqp and ma27 still do not 'clean', but we will never change anything in the source code there, so that should be less of a problem.
