### ISSUE TITLE
Error creating error message

### ISSUE THREAD

**Issue by ChrisK2111** [acados/acados#623]
Hi together!

There is a small bug in acados_ocp.m lines 136 to 142:
            try
                % create C object
                obj.C_ocp = ocp_create(obj.model_struct, obj.opts_struct);
            catch _**ex**_
                str = sprintf('Exception:\n\t%s\n\t%s\n',ex.identifier,ex.message);
                error(str);
            end

The **_ex_** is missing.

**Comment by FreyJo** [comment]
Thanks for reporting, I already merged that fix yesterday though:
https://github.com/acados/acados/pull/619
https://github.com/acados/acados/commit/7f0744acb5132693d1cf21808ec8f501d916fbe6
