### ISSUE TITLE
Acados with python interface 

### ISSUE THREAD

**Issue by Mosolim** [acados/acados#630]
I just begin using acados with python and I have an issue  can someone help 
![Screenshot_20200826_164927](https://user-images.githubusercontent.com/60929673/91461964-eb0eca00-e889-11ea-9f59-f56500cc1ace.png)
![Screenshot_20200826_163454](https://user-images.githubusercontent.com/60929673/91461965-eba76080-e889-11ea-820b-bc6bc4088cae.png)

now i get this error
![error](https://user-images.githubusercontent.com/60929673/91470030-7a20df80-e894-11ea-8268-3f7c4e1d55b6.png)

Thanks in advance

**Comment by Mosolim** [comment]
however it works from the terminal 
[output.txt](https://github.com/acados/acados/files/5137444/output.txt)

**Comment by FreyJo** [comment]
The forum is the right place for these kind of questions.
https://discourse.acados.org/t/python-and-acados-interface/238/2
