### ISSUE TITLE
Condensing with variable dimensions

### ISSUE THREAD

**Issue by rienq** [acados/acados#7]
The current implementation of the condensing+qpOASES solver does not yet work with variable state and control dimensions on the different stages (even though you could define different dimensions in the current version of the interface).

**Comment by roversch** [comment]
@giaf @dkouzoup Has condensing with changing dimensions ever been implemented before? It should not be too hard, but it's gonna be tedious.

**Comment by giaf** [comment]
I did, I have a version in hpmpc implementing the O(N^2) and O(n_x^3) condensing algorithm with changing state and input dimensions.

**Comment by dkouzoup** [comment]
Once IFAC deadline is passed, I can assist @gianf with this implementation if that helps to speed up things.

**Comment by roversch** [comment]
Also see #9

**Comment by roversch** [comment]
Supported by the HPIPM interface
