### ISSUE TITLE
Typo in ocp_create

### ISSUE THREAD

**Issue by bmasterk** [acados/acados#720]
Hey!

I think there might be a small typo in the following lines.

https://github.com/acados/acados/blob/25c678205c61e3dc42034ceb5d9b9dbae5ef565d/interfaces/acados_matlab_octave/ocp_create.c#L2036
https://github.com/acados/acados/blob/25c678205c61e3dc42034ceb5d9b9dbae5ef565d/interfaces/acados_matlab_octave/ocp_create.c#L2037

It references to the matrix "Jsbx_matlab", but it should reference to "Jsbx_e_matlab"

Best regards
Björn

**Comment by FreyJo** [comment]
Hi Björn,

thanks for reporting, I just pushed a fix:
https://github.com/acados/acados/commit/8bef23e31777d44f855ae44eb8154994f5bdd6fc

Cheers,
Jonathan
