### ISSUE TITLE
sim_method_jac_reuse missing in acados_ocp_opts

### ISSUE THREAD

**Issue by bmasterk** [acados/acados#733]
Hello there,

I just saw that the ocp option "_sim_method_jac_reuse_" is not interfaced for MATLAB in "_acados_ocp_opts.m_"

In [https://github.com/acados/acados/blob/4ad361a47b7a2b4caaef50b6a025fbc77d495f06/interfaces/acados_matlab_octave/acados_ocp_opts.m](url)

I think it should be possible to just add the following code in  "_acados_ocp_opts.m_"
```
            elseif (strcmp(field, 'sim_method_jac_reuse'))
                obj.opts_struct.sim_method_jac_reuse = value;
```

Best regards
Björn

**Comment by FreyJo** [comment]
Hi Björn,

I made this option available in the Matlab template workflow in this PR:
https://github.com/acados/acados/pull/734

Best,
Jonathan
