### ISSUE TITLE
AcadosOcpSolver(..., build=False) fails

### ISSUE THREAD

**Issue by krepa098** [acados/acados#741]
```AcadosOcpSolver(..., build=False)``` (introduced in 38c2d62651100673061d19d90a27ae857358727f) fails as it relies on some undefined variables

```
Traceback (most recent call last):
  File "generate_c_code.py", line 168, in <module>
    acados_solver = AcadosOcpSolver(ra, json_file = 'acados_ocp.json', build=False)
  File "/acados/interfaces/acados_template/acados_template/acados_ocp_solver.py", line 813, in __init__
    self.shared_lib_name = f'{code_export_dir}/libacados_ocp_solver_{model.name}.so'
UnboundLocalError: local variable 'code_export_dir' referenced before assignment
Exception
```
Furthermore, most of the code in AcadosOcpSolver relies on generating/building the OCP. I think it would be beneficial to split AcadosOcpSolver, in some class dealing with code generation only, and another one doing everything what remains. @HaraldSchafer

**Comment by HaraldSchafer** [comment]
I'm working on that actually, I will open a PR soon!

https://github.com/acados/acados/pull/735

This has it mostly seperated, but there's still some work to be done. And I want to open a PR with just the building stuff different.
