### ISSUE TITLE
Acados can't run on my Windows 10 in Matlab

### ISSUE THREAD

**Issue by Faust-Wang** [acados/acados#755]
I compiled successfully （mingw32-make.exe install） according to the tutorial （https://docs.acados.org/installation/index.html）
The MATLAB example, however, does not work. 
1.Error:  `MEX could not find the library 'acados' specified with the -l option.  
MEX has searched for files with one of the following names: 
 libacados.a
acados.lib
libacados.lib
Verify that the library name is correct.  If the library is not there  
In an existing path, use the -l option to specify the path.   `
I modify line 169 of 'ocp_compile_interface.m' (<'-lacados', '-lhpipm', '-lblasfeo',libs.osqp> to <'-Lacados', '-Lhpipm', '-Lblasfeo','-Losqp'>). 
Ok, this error is gone. But the second erroecame out and I couldn't fix it.
2. Error:
` Structure detection for path cost
Cost function is quadratic -> Reformulating as linear_ls cost.
reformulated cost term in linear least squares form with:
cost = 0.5 * || Vx * x + Vu * u + Vz * z - y_ref ||_W
Vx
     1     0     0     0
     0     1     0     0
     0     0     1     0
     0     0     0     1
     0     0     0     0
Vu
     0
     0
     0
     0
     1
Vz
W
   1.0e+03 *

    2.0000         0         0         0         0
         0    2.0000         0         0         0
         0         0    0.0000         0         0
         0         0         0    0.0000         0
         0         0         0         0    0.0000

y_ref
     0
     0
     0
     0
     0
y (symbolic)
[p, theta, v, dtheta, F]
NOTE: These numerical values can be updated online using the appropriate setters.
Structure detection for terminal cost term
Cost function is quadratic -> Reformulating as linear_ls cost.
reformulated cost term in linear least squares form with:
cost = 0.5 * || Vx * x + Vu * u + Vz * z - y_ref ||_W
Vx
     1     0     0     0
     0     1     0     0
     0     0     1     0
     0     0     0     1
Vu
     0
     0
     0
     0
Vz
W
   1.0e+03 *

    2.0000         0         0         0
         0    2.0000         0         0
         0         0    0.0000         0
         0         0         0    0.0000
y_ref
     0
     0
     0
     0
y (symbolic)
[p, theta, v, dtheta]
NOTE: These numerical values can be updated online using the appropriate setters.
Constraint detection for path constraints.
constraint 1 is reformulated as bound on u.
F
compiling E:\Project\acados\examples\acados_matlab_octave\..\..\interfaces\acados_matlab_octave\ocp_create.c
Compile using the 'MinGW64 Compiler (C)'.  
Error using mex  
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x27e): undefined reference to
`ocp_nlp_plan_create'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x6e1): undefined reference to
`ocp_nlp_config_create'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x751): undefined reference to
`ocp_nlp_dims_create'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x7e1): undefined reference to
`ocp_nlp_dims_set_opt_vars'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x869): undefined reference to
`ocp_nlp_dims_set_opt_vars'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x8d1): undefined reference to
`ocp_nlp_dims_set_opt_vars'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x968): undefined reference to
`ocp_nlp_dims_set_cost'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x9cf): undefined reference to
`ocp_nlp_dims_set_cost'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0xa30): undefined reference to
`ocp_nlp_dims_set_cost'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0xa90): undefined reference to
`ocp_nlp_dims_set_constraints'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0xb16): undefined reference to
`ocp_nlp_dims_set_constraints'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0xb7e): undefined reference to
`ocp_nlp_dims_set_constraints'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0xc09): undefined reference to
`ocp_nlp_dims_set_constraints'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0xc96): undefined reference to
`ocp_nlp_dims_set_constraints'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0xcfe): more undefined
references to `ocp_nlp_dims_set_constraints' follow
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x1307): undefined reference to
`ocp_nlp_dims_set_opt_vars'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x136d): undefined reference to
`ocp_nlp_dims_set_constraints'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x1384): undefined reference to
`ocp_nlp_solver_opts_create'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x13da): undefined reference to
`ocp_nlp_solver_opts_set'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x1438): undefined reference to
`ocp_nlp_solver_opts_set'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x148c): undefined reference to
`ocp_nlp_solver_opts_set'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x14e4): undefined reference to
`ocp_nlp_solver_opts_set'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x1587): undefined reference to
`ocp_nlp_solver_opts_set'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x15d9): more undefined
references to `ocp_nlp_solver_opts_set' follow
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x1c82): undefined reference to
`ocp_nlp_in_create'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x1d97): undefined reference to
`ocp_nlp_in_set'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x1db5): undefined reference to
`ocp_nlp_cost_model_set'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x1ddd): undefined reference to
`ocp_nlp_out_create'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x1df0): undefined reference to
`ocp_nlp_solver_create'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x1e06): undefined reference to
`ocp_nlp_out_create'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x21bb): undefined reference to
`ocp_nlp_cost_model_set'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x234f): undefined reference to
`ocp_nlp_cost_model_set'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x2470): undefined reference to
`ocp_nlp_cost_model_set'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x257c): undefined reference to
`ocp_nlp_cost_model_set'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x269f): undefined reference to
`ocp_nlp_cost_model_set'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x27ab): more undefined
references to `ocp_nlp_cost_model_set' follow
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x2cfb): undefined reference to
`ocp_nlp_out_set'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x2d85): undefined reference to
`ocp_nlp_out_set'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x2e5b): undefined reference to
`ocp_nlp_constraints_model_set'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x2f3a): undefined reference to
`ocp_nlp_constraints_model_set'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x2ff2): undefined reference to
`ocp_nlp_constraints_model_set'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x30a7): undefined reference to
`ocp_nlp_constraints_model_set'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x328a): undefined reference to
`ocp_nlp_constraints_model_set'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x3446): more undefined
references to `ocp_nlp_constraints_model_set' follow
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x50cb): undefined reference to
`ocp_nlp_dims_set_dynamics'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x50e5): undefined reference to
`ocp_nlp_dims_set_dynamics'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x50ff): undefined reference to
`ocp_nlp_dims_set_dynamics'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x5119): undefined reference to
`ocp_nlp_dims_set_dynamics'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x513a): undefined reference to
`ocp_nlp_dims_set_dynamics'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x535e): undefined reference to
`ocp_nlp_constraints_model_set'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x541e): undefined reference to
`ocp_nlp_constraints_model_set'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x54d2): undefined reference to
`ocp_nlp_constraints_model_set'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x55f6): undefined reference to
`ocp_nlp_solver_opts_set_at_stage'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x56e6): undefined reference to
`ocp_nlp_solver_opts_set_at_stage'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x57ca): undefined reference to
`ocp_nlp_solver_opts_set_at_stage'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x58ba): undefined reference to
`ocp_nlp_solver_opts_set_at_stage'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x59a9): undefined reference to
`ocp_nlp_solver_opts_set_at_stage'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x5aa9): more undefined
references to `ocp_nlp_solver_opts_set_at_stage' follow
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x5b78): undefined reference to
`ocp_nlp_cost_model_set'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x5c2d): undefined reference to
`ocp_nlp_cost_model_set'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x5cf5): undefined reference to
`ocp_nlp_cost_model_set'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x5d3c): undefined reference to
`ocp_nlp_solver_opts_set'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x5d76): undefined reference to
`ocp_nlp_solver_opts_set'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x5db9): undefined reference to
`ocp_nlp_solver_opts_set'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x5e0d): undefined reference to
`ocp_nlp_out_set'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x6056): undefined reference to
`ocp_nlp_solver_opts_set'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x63eb): undefined reference to
`ocp_nlp_cost_model_set'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x64e0): undefined reference to
`ocp_nlp_cost_model_set'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x65df): undefined reference to
`ocp_nlp_cost_model_set'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x66cb): undefined reference to
`ocp_nlp_cost_model_set'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x67cb): undefined reference to
`ocp_nlp_cost_model_set'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x688a): more undefined
references to `ocp_nlp_cost_model_set' follow
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x6bbf): undefined reference to
`ocp_nlp_out_set'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x6bf3): undefined reference to
`ocp_nlp_dims_set_opt_vars'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x6cfc): undefined reference to
`ocp_nlp_solver_opts_set_at_stage'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x6dc2): undefined reference to
`ocp_nlp_solver_opts_set_at_stage'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x6e79): undefined reference to
`ocp_nlp_solver_opts_set_at_stage'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x6f30): undefined reference to
`ocp_nlp_solver_opts_set_at_stage'
C:\Users\XXX\AppData\Local\Temp\mex_4329624523067918_22816\ocp_create.obj:ocp_create.c:(.text+0x6fe7): undefined reference to
`ocp_nlp_solver_opts_set_at_stage'
collect2.exe: error: ld returned 1 exit status
Error  ocp_compile_interface ( (line 169)
        mex(mex_flags, FLAGS, LDFLAGS, COMPDEFINES, COMPFLAGS, acados_include, acados_interfaces_include, external_include,
        blasfeo_include, hpipm_include,...
Error  acados_ocp  (line 181)
                ocp_compile_interface(obj.opts_struct);
Error minimal_example_ocp (line 107)
ocp = acados_ocp(ocp_model, ocp_opts); `
What should I do about this error?
I tried Acados on an Ubuntu virtual machine and it worked

>

**Comment by FreyJo** [comment]
Can you check in the `mex` call in https://github.com/acados/acados/blob/master/interfaces/acados_matlab_octave/ocp_compile_interface.m
if the paths that are arguments for `mex` are correct?

**Comment by Faust-Wang** [comment]
Thank you for your reply. How can I check it, please?  Can you give a routine? I need mex(??????).

**Comment by FreyJo** [comment]
I guess you are using Matlab and the error occurs here:
https://github.com/acados/acados/blob/master/interfaces/acados_matlab_octave/ocp_compile_interface.m#L169
So, set a break point before that and check the arguments of this `mex` call.

**Comment by Faust-Wang** [comment]
Yes. The initial error indicates that the associated library cannot be found.1.Error: MEX could not find the library 'acados' specified with the -l option. MEX has searched for files with one of the following names: libacados.a acados.lib libacados.lib Verify that the library name is correct. If the library is not there In an existing path, use the -l option to specify the path.
I modify line 169 of 'ocp_compile_interface.m' (<'-lacados', '-lhpipm', '-lblasfeo',libs.osqp> to <'-Lacados', '-Lhpipm', '-Lblasfeo','-Losqp'>).
Ok, this error is gone. But the second erroecame out and I couldn't fix it.
Now, The parameter is `mex(mex_flags,` FLAGS, LDFLAGS, COMPDEFINES, COMPFLAGS, acados_include, acados_interfaces_include, external_include, blasfeo_include, hpipm_include, acados_lib_path, '-Lacados', '-Lhpipm', '-Lblasfeo', libs.qpoases,libs.qpdunes, '-Losqp', libs.hpmpc, libs.ooqp, mex_files{ii}, '-outdir', opts.output_dir)`
However, a new error has emerged as mentioned above

**Comment by Faust-Wang** [comment]
I checked all the parameters as follows:
`mex_flags`：An empty 0 by 0 char array =============I guess there's something wrong with  `mex_flags = getenv('ACADOS_MEX_FLAGS')` 
`FLAGS`: 'CFLAGS=$CFLAGS -std=c99 -DACADOS_WITH_OSQP'
`LDFLAGS`:  'LDFLAGS=$LDFLAGS'
`COMPDEFINES`: 'COMPDEFINES=$COMPDEFINES -DACADOS_WITH_OSQP'
`COMPFLAGS`: 'COMPFLAGS=$COMPFLAGS'
`acados_include`: '-IE:\Project\acados\examples\acados_matlab_octave\..\..'
`acados_interfaces_include`:  '-IE:\Project\acados\examples\acados_matlab_octave\..\..\interfaces'
`external_include`: '-IE:\Project\acados\examples\acados_matlab_octave\..\..\external'
``:
``:
``:

**Comment by FreyJo** [comment]
Ah, I see, you should not do this:
> I modify line 169 of 'ocp_compile_interface.m' (<'-lacados', '-lhpipm', '-lblasfeo',libs.osqp> to <'-Lacados', '-Lhpipm', '-Lblasfeo','-Losqp'>).

from the gcc docu, how -L and -l should be used:
```
    gcc source.c --output executable -Iheader_path -Llibrary_path -llibrary_name
```

Did you check what is in your folder `Project\acados\lib`, i.e. if all libs are compiled successfully?

**Comment by Faust-Wang** [comment]
As you said, the lib folder has only one file `link_libs.json`.
However, following the two steps of the tutorial(`https://docs.acados.org/installation/index.html`), no errors were reported:
`cmake.exe -G "MinGW Makefiles" -DACADOS_INSTALL_DIR="$ACADOS_INSTALL_DIR" -DBUILD_SHARED_LIBS=OFF -DACADOS_WITH_OSQP=ON ..`
`mingw32-make.exe -j4`
`mingw32-make.exe install`
These operations were all successful.
Which lib should I compile separately? Whether to use this command `gcc source.c --output executable -Iheader_path -Llibrary_path -llibrary_name`

**Comment by FreyJo** [comment]
It seems like passing the argument "-DACADOS_INSTALL_DIR="$ACADOS_INSTALL_DIR"" to CMake didn't work correctly.
You can of course manually copy the lib files into the folder `acados/lib`.

**Comment by Faust-Wang** [comment]
This is true. This example is ready to run.
But I still get this -L error when compiling other project files.
error: `MEX could not find the library 'cl_swarming' specified with the -l option.  
MEX has searched for files with one of the following names:  
libcl_swarming.a  
cl_swarming.lib  
libcl_swarming.lib  
Verify that the library name is correct.  If the library is not there  
In an existing path, use the -l option to specify the path. `
I checked and found that the C code matlab generated by Casadi could not compile into a.lib file.  So acados can't call.lib  
Do you have a solution for this situation

**Comment by FreyJo** [comment]
> I checked and found that the C code matlab generated by Casadi could not compile into a.lib file.

Why is that? What was the error when compiling the model?

**Comment by Faust-Wang** [comment]
> > I checked and found that the C code matlab generated by Casadi could not compile into a.lib file.
> 
> Why is that? What was the error when compiling the model?

The error is very similar to the one mentioned above：error: `MEX could not find the library 'cl_swarming' specified with the -l option. MEX has searched for files with one of the following names: libcl_swarming.a cl_swarming.lib libcl_swarming.lib Verify that the library name is correct. If the library is not there In an existing path, use the -l option to specify the path.` 
However, I can compile `cl_swarming.so` files automatically on Ubuntu.
Therefore, I would like to ask: how should I handle the error with ` the library is not there In an existing path, use the -l option to specify the path`?

**Comment by FreyJo** [comment]
Is the model lib compiled successfully?
I.e. is a library with one of the names `libcl_swarming.a cl_swarming.lib libcl_swarming.lib` in your `build` folder?
If not, there must have been an error before the one you posted..

**Comment by Faust-Wang** [comment]
Unfortunately, I still haven't compiled successfully.  I don't know why ` lib` doesn't compile.  On Ubuntu I had no trouble compiling the `so` .
