### ISSUE TITLE
How to set constraints on some (not all) states? 

### ISSUE THREAD

**Issue by Orca-bit** [acados/acados#774]
Hi, for example, if I have states `x, y, z`, how to set the `lbx` and `ubx` that only work on `y`, should I specify the `idxbx` at the same time?

**Comment by FreyJo** [comment]
Hi,
yes you should use `idxbx`.

For example, assuming your state is
```
x = [x1, x2, x3]
```
and you want to only constrain `x2` to be within the interval `[ lx2, ux2]`, you need to set:
`idxbx = [1] lbx = [lx2], ubx = [ux2]`.
