### ISSUE TITLE
Python script testing multiple solvers with OpenMP parallelization fail

### ISSUE THREAD

**Issue by FreyJo** [acados/acados#782]
I realized that on the current master branch https://github.com/acados/acados/commit/91a01d4c8db13b5de0d7c600eec72a96b3b5d771
When compiling acados with openmp, the Python test scripts that test multiple solvers are failing, e.g.
https://github.com/acados/acados/blob/91a01d4c8db13b5de0d7c600eec72a96b3b5d771/examples/acados_python/tests/main_test.py
I also went back to the version 0.1.6 and got the same behavior.
It seems like the number of threads is restored on every exit of the SQP method.
Maybe someone with more experience with openmp knows what could be the issue.

**Comment by schwieni** [comment]
@FreyJo: this issue should be fixed with PR #785

**Comment by FreyJo** [comment]
Thanks!
