### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by DrShIkIgAmy** [acados/acados#792]
Since I synced repo with master yesterday, I've receiving segmentation fault errors. The errors refer to ocp_liniear_search function. 
![image](https://user-images.githubusercontent.com/62403955/156886295-63a572fc-157a-4093-9a40-2cc691e1c074.png)
I have no idea what is going on. The errors still as when parallel on as when it's off.

**Comment by FreyJo** [comment]
Hi,
thanks for reporting this!
It seems related to globalization.
So, it could be related to this PR https://github.com/acados/acados/pull/772 
A bit more context is needed to look into this.
Can you send a minimal example to reproduce this?
