### ISSUE TITLE
Problem when compling the minimal_example_ocp.m

### ISSUE THREAD

**Issue by ZionLIU-hit** [acados/acados#814]
Hi there,

I have just installed acados for Windows following the user manual and error occurs when I run the the `minimal_example_ocp.m`.
I set a breakpoint between 
`compile_status = system(compile_command);`                    
`if compile_status ~= 0`  in `ocp_generate_casadi_ext_fun.m`
and it returns that:
`found compiled acados MEX interface  `
`239 compile_status = system(compile_command);    `
`'gcc' is not recognized as an internal or external command or batch file.`

I have added the PATH variables as:
`C:\ProgramData\MATLAB\SupportPackages\R2022a\3P.instrset\mingw_w64.instrset\bin;
C:\ProgramData\MATLAB\SupportPackages\R2022a\3P.instrset\mingw_w64.instrset\x86_64-w64-mingw32\bin`
and mex has been set as
`K>> mex -setup c++
MEX 配置为使用 'MinGW64 Compiler (C++)' 以进行 C++ 语言编译。`

Can anyone help me?
Thanks in advance.

**Comment by FreyJo** [comment]
what was the problem?
why did you close this issue?

**Comment by ZionLIU-hit** [comment]
After I restarted PC the next day, I found it works..
