### ISSUE TITLE
swarming solution failed

### ISSUE THREAD

**Issue by johnwaneboy** [acados/acados#822]
i run the demo of   example_sim.m, example_ocp.m, example_closed_loop.m      in acados/examples/acados_matlab_octave/swarming
 but it always solution  failed ~~~~

**Comment by johnwaneboy** [comment]
![image](https://user-images.githubusercontent.com/40469098/169248213-661b73ee-bbc6-4e76-87ec-1e6ecb4f391a.jpeg)

**Comment by FreyJo** [comment]
On which acados version are you?
What error do you get when running `example_sim`?

**Comment by johnwaneboy** [comment]
example_sim  could run sucessfully
![image](https://user-images.githubusercontent.com/40469098/169289504-e7abb564-43d2-49a3-9e35-83d9777344cf.jpeg)

**Comment by FreyJo** [comment]
ok, just the `example_ocp` doesn't work for you.
Can you switch to the latest acados version and check if it works?
The version you have seems at least 6 months old.

**Comment by johnwaneboy** [comment]
thanks ！ I will try later, and I have build the the same model in python + ubuntu, but if I set the path constraints（con_h_expr） such as the minimum distance between agents, then solution will fail, even I set the lh to infinitesimal and the uh to infinity.

**Comment by johnwaneboy** [comment]
I have switched to the latest version， the example_closed_ loop.  and   example_ ocp.m stil solution failed.

**Comment by FreyJo** [comment]
Did you also update the submodules?
What OS are you using?
Can you copy the output of the failing example here?

**Comment by johnwaneboy** [comment]
Ihave reinstalled the acados,  my environment is ubuntu 18.06 with python 3.6. 
when i run my demo, if there is no constraints, it works well, but when i add constraint, it return status 4

![image](https://user-images.githubusercontent.com/40469098/169318865-85704a01-e6f5-490b-b85a-e309675ae25e.jpeg)

**Comment by johnwaneboy** [comment]
Thank you very much for helping solve the problem . What other information can I supply to help you solve the problem ?

**Comment by sandmaennchen** [comment]
Is this still an issue? The example works for me using the current acados version.
