### ISSUE TITLE
Python interface: issue with Apple M1 chip

### ISSUE THREAD

**Issue by tomcattiger1230** [acados/acados#842]
Hi,

has anyone tried to implement and test on Apple M1 chip?

**Comment by FreyJo** [comment]
Hi,
acados has been tested on MacOS with the MacBookPro version just before the M1 chip.
Plus there is a dedicated BLASFEO target for M1, which still should be added to CMake though, https://github.com/giaf/blasfeo/blob/master/Changelog.txt#L57
But with `GENERIC` BLASFEO target it should work fine.

**Comment by tomcattiger1230** [comment]
> Hi,
> acados has been tested on MacOS with the MacBookPro version just before the M1 chip.
> Plus there is a dedicated BLASFEO target for M1, which still should be added to CMake though, https://github.com/giaf/blasfeo/blob/master/Changelog.txt#L57
> But with `GENERIC` BLASFEO target it should work fine.

Hi, I've tested it with MacBook Pro Intel-Version. But now it faces arm64 Probem (no work with x86_64)

**Comment by tomcattiger1230** [comment]
Hi, 

clear to say, if one uses C++ it is ok. But if one uses Python, it comes with error 
ld: warning: ignoring file /Users/weiluo/Develop/github/acados/lib/libacados.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64

**Comment by tomcattiger1230** [comment]
Hi, 

I've noticed that it is caused by ctypes.CDLL
a = CDLL('/Users/xxx/Develop/github/acados/lib/libacados.dylib')

=>.  OSError: dlopen(/Users/xxx/Develop/github/acados/lib/libacados.dylib, 0x0006): tried: ''/Users/xxx/Develop/github/acados/lib/libacados.dylib' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64)))

**Comment by FreyJo** [comment]
It seems that the Python you are using is `x86_64` emulated, but the `dylib` is compiled for `arm64` and thus not compatible.
I think you could try to either make the Python native `arm64` or compile the `dylib` for `x86_64`.

**Comment by tomcattiger1230** [comment]
> It seems that the Python you are using is `x86_64` emulated, but the `dylib` is compiled for `arm64` and thus not compatible.
> I think you could try to either make the Python native `arm64` or compile the `dylib` for `x86_64`.

Thanks. I've found the problem. It works now.

**Comment by FreyJo** [comment]
Could you explain, how you solved it here, in case someone else has this issue?

**Comment by tomcattiger1230** [comment]
> 

I use anaconda to set up Python env. But the default download from anaconda for macOS currently is still for x64_86, and I've not noticed about that. One can choose manually the version for arm64. After reinstalling anaconda for arm64, this library problem is solved.
