### ISSUE TITLE
the demo minimal_example_ocp.py occurs error

### ISSUE THREAD

**Issue by chesily** [acados/acados#862]
Dear all,
when i follow the guide to install python Interface, the demo minimal_example_ocp.py occurs error.
![2022-09-27 16-50-20 的屏幕截图](https://user-images.githubusercontent.com/46998045/192480798-c8af1a3d-bdaf-4780-a3e2-afe3d4439cac.png)
but the file libqpOASES_e.so.3.1 indeed is in <acados_root>/lib, what is wrong?

regards,
cheslee

**Comment by FreyJo** [comment]
Is your `LD_LIBRARY_PATH` set correctly?

**Comment by chesily** [comment]
> 



> Is your `LD_LIBRARY_PATH` set correctly?

the reason causing this error is that i don't understand how to set multi` LD_LIBRARY_PATH`

thank you

now the question has been solved
