### ISSUE TITLE
Output dimension of implicit dynamics

### ISSUE THREAD

**Issue by FranekStark** [acados/acados#885]
Hallo everyone,
I'm a bit confused about the size of implicit dynamics in acados solver.
In https://github.com/acados/acados/blob/master/docs/problem_formulation/problem_formulation_ocp_mex.pdf it is stated that the output dimension of the function (In my understanding the number of implicit functions) has to equal the number of states (plus the number of algebraic states). My problem is, that I have a dynamic description of a system with 12 kinematic constraints (each one is its one fully implicit DAE). However, the number of states is bigger.
Do I need to provide a implicit function for each state or how does this work?

**Comment by FreyJo** [comment]
Hi,
the implicit integration methods in acados aim to solve index-1 DAEs.
Thus, the Jacobian d f_impl / d(xdot, z) has to be full rank.
Maybe you don't have an index-1 DAE and need to do index-reduction.
