### ISSUE TITLE
Missing source file in the creation of the MODEL_OBJ using CMake build

### ISSUE THREAD

**Issue by shelddin** [acados/acados#915]
I am using acados in a CMake project. the issue is that writing the control problem using the python interface and using the ERK integrator with a CMake build produces undefined references.

To reproduce the problem,

In the pendulum_on_cart example, in [example_solution_sens_closed_loop.py](https://github.com/acados/acados/blob/9f662fb4a16d373a7fed6a91855e9f15fd101cfe/examples/acados_python/pendulum_on_cart/example_solution_sens_closed_loop.py), adding

`
from acados_template import ocp_get_default_cmake_builder, sim_get_default_cmake_builder
`

and modifying line [108](https://github.com/acados/acados/blob/9f662fb4a16d373a7fed6a91855e9f15fd101cfe/examples/acados_python/pendulum_on_cart/example_solution_sens_closed_loop.py#L108) and 109 to 

```
acados_ocp_solver = AcadosOcpSolver(ocp, json_file = 'acados_ocp_' + model.name + '.json', cmake_builder=ocp_get_default_cmake_builder())
acados_integrator = AcadosSimSolver(ocp, json_file = 'acados_ocp_' + model.name + '.json', cmake_builder=sim_get_default_cmake_builder())

```

and using `integrator_type = 'ERK'`

Running this will have an `undefined symbol: pendulum_ode_expl_vde_adj_sparsity_in`

This could be solved by adding the missing source file in the creation of the object library of the model in the generated CMakeLists.

```
# model
set(MODEL_SRC
    pendulum_ode_model/pendulum_ode_expl_ode_fun.c
    pendulum_ode_model/pendulum_ode_expl_vde_forw.c
    pendulum_ode_model/pendulum_ode_expl_vde_adj.c                   # added line
)

```

acados: v0.2.0
ubuntu: 20.04

**Comment by FreyJo** [comment]
Thanks for reporting!
It should be changed in the template that is generating the code.
I pushed a fix here:
https://github.com/acados/acados/pull/916
