### ISSUE TITLE
How to generate C code

### ISSUE THREAD

**Issue by Teruru-52** [acados/acados#937]
Dear FreyJo

I want to utilize `acados` for solving OCP in c language, on Ubuntu 22.04.
I have read the acados documentation but could not figure out how to generate c code.
Here is my understanding.

0. Create a python file for c code generation.
1. Describe problem formulation like `examples/acados_python/getting_started/minimal_example_ocp.py`
2. Call  `ocp.generate()` to generate `acados_ocp_nlp.json`.
3. Generate c code from `acados_ocp_nlp.json`. (I don't know)

Please tell me how to generate c code correctly.
Best regards.

**Comment by FreyJo** [comment]
Hi,
the workflow is to prototype a solver in Python.
Then you automatically have a `c_generated_code` folder, with a minimal main file that shows how to use it in a `C` environment.
Good luck!
