### ISSUE TITLE
Use acados  to form optimized problem with dual variables and external cost function

### ISSUE THREAD

**Issue by zhuzaicong** [acados/acados#947]
Hi~  First of all ,  thanks for providing examples to get started with acados. I have gone through all the cases carefully, but still failed to form my optimized problem. I am trying to solve the following problem:
![image](https://github.com/acados/acados/assets/5784819/f00c175f-d7a8-4f05-a995-b5af0f1ccf69)

My cost function has some difference with the above formula.  i tried using control varibles to store lambdas and  mius which is dual variables. and using algebraic variables to store the d_min.  

[my_code.zip](https://github.com/acados/acados/files/12077416/my_code.zip)

It output log like “**error: ocp_nlp_cost_external_dims_get: attempt to get dimensions of non-existing field ny**” when run with python, i don‘’t know what goes wrong. maybe i have some misconceptions about the acados cost function.  

Thanks in advance!

**Comment by sandmaennchen** [comment]
Hi :wave: 
please check the [acados problem formulation](https://github.com/acados/acados/blob/master/docs/problem_formulation/problem_formulation_ocp_mex.pdf)! And consider discussing your formulation in the [acados forum](https://discourse.acados.org/).
