### ISSUE TITLE
Error while testing minimal_example_ocp: No file or directory found: /acados_layout.json

### ISSUE THREAD

**Issue by haotian21** [acados/acados#978]
Hi everyone, 

when I try to run **minimal_example_ocp** from **/acados/examples/acados_python/getting_started/minimal_example_ocp.py** to test whether or not I have set up everything correctly, I keep getting the following error: 

**No such file or directory: ' /acados/interfaces/acados_template/acados_template/acados_layout.json'**

I checked the  **/acados/interfaces/acados_template/acados_template/** folder and the **acados_layout.json** is indeed in there. Could someone possibly help me? 

Thank you in advance.

**Comment by FreyJo** [comment]
I don't know why that issue occurred for you.
However, I recently removed the layout from the python interface entirely, in https://github.com/acados/acados/pull/998
Thus, this is outdated.
Please open a new issue if you still have problem.
Cheers!
