### ISSUE TITLE
Python interface installation issues

### ISSUE THREAD

**Issue by Azircarry** [acados/acados#985]
I'm installing the python interface of acados in ubuntu18.04 system, python version is 3.6, when I installed according to the official document, there was an error in the following command, which caused the download of acados_template package to fail, but when I downloaded other packages, it can be downloaded successfully, can you help me，thanks

When I execute the following command：
pip3 install acados_template -i http://pypi.douban.com/simple/ --trusted-host pypi.douban.com

The following error will occur：
Collecting acados_template
  Could not find a version that satisfies the requirement acados_template (from versions: )
No matching distribution found for acados_template
![110803bb4c4088c4ad000dd32eddee0](https://github.com/acados/acados/assets/114214508/39b28ebc-bbc1-4ac9-8ef9-943c68b53156)

**Comment by FreyJo** [comment]
Sorry, you did not follow the installation instructions of the Python interface properly.
https://docs.acados.org/python_interface/index.html#installation

**Comment by Azircarry** [comment]
Hello, thanks for your reply, but even if I install according to the installation instructions, I still get the following error, I don't know what the reason is, in addition, I went to the python third-party package official website to check, and I didn't find acados_template
pack，Sorry to bother you
![}{4CG1$%CXM{RJZDYC%2N$V](https://github.com/acados/acados/assets/114214508/e045ad2b-f038-43ac-a98a-841a6861c278)

**Comment by Azircarry** [comment]
Thanks for your reply？It is ok

**Comment by Azircarry** [comment]
Thanks for your reply!  It is ok。
