### ISSUE TITLE
Error in "make examples_c" 

### ISSUE THREAD

**Issue by GianlinoZ** [acados/acados#990]
Hello, I have installed acados by following the instructions in https://docs.acados.org/installation/index.html#linux-mac. However, in the last step when I typed "make examples_c" in shell, it gave me an error when building the target of "regularization", after successfully building "wind_turbine_nmpc build" 

Here is the info displayed in the shall:

gcc -o wind_turbine_nmpc.out wind_turbine_nmpc.o  wt_model_nx6/nx6p2/wt_nx6p2_expl_ode_fun.o wt_model_nx6/nx6p2/wt_nx6p2_expl_vde_for.o wt_model_nx6/nx6p2/wt_nx6p2_impl_ode_fun.o wt_model_nx6/nx6p2/wt_nx6p2_impl_ode_fun_jac_x_xdot.o wt_model_nx6/nx6p2/wt_nx6p2_impl_ode_fun_jac_x_xdot_u.o wt_model_nx6/nx6p2/wt_nx6p2_impl_ode_jac_x_xdot_u.o wt_model_nx6/nx6p2/wt_nx6p2_phi_fun.o wt_model_nx6/nx6p2/wt_nx6p2_phi_fun_jac_y.o wt_model_nx6/nx6p2/wt_nx6p2_phi_jac_y_uhat.o wt_model_nx6/nx6p2/wt_nx6p2_f_lo_fun_jac_x1k1uz.o wt_model_nx6/nx6p2/wt_nx6p2_get_matrices_fun.o -L/home/marvin/acados/lib -lacados -lhpipm -lqpOASES_e -lblasfeo -lm -lblas -llapack

 Example wind_turbine_nmpc build complete.

gcc -O2 -fPIC -DACADOS_WITH_QPOASES -DACADOS_WITH_C_INTERFACE -DMEASURE_TIMINGS -I/home/marvin/acados -I/home/marvin/acados/interfaces -I/home/marvin/acados/include -I/home/marvin/acados/external/blasfeo/include -I/home/marvin/acados/external/hpipm/include -I/home/marvin/acados/external/hpmpc/include -I/home/marvin/acados/external/qpoases/include -I/home/marvin/acados/include/qore/include -I/home/marvin/acados/external/qpdunes/include -I/home/marvin/acados/external/osqp/include -std=c99   -c -o regularization.o regularization.c
regularization.c: In function ‘main’:
regularization.c:108:9: error: too many arguments to function ‘config->opts_set’
  108 |         config->opts_set(config, dims, opts, "epsilon", &epsilon);
      |         ^~~~~~
make[1]: *** [<builtin>: regularization.o] Error 1
make[1]: Leaving directory '/home/marvin/acados/examples/c'
make: *** [Makefile:280: examples_c] Error 2

In case you may need more info, my gcc is 11.4.0 and OS is Ubuntu 22.04 LTS.

I was wondering if this problem is merely caused by a bug in the example regularization (in line 108 config->opts_set(config, dims, opts, "epsilon", &epsilon) or there is something wrong with my installation?

Many thanks in advance!

**Comment by FreyJo** [comment]
Hi,
I addressed the issue in the linked commit.
Note that the CMake build system is better tested than Make.
Cheers!
